name: Build and Test

# This workflow will run on main branch and on any pull requests targeting main
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:1.16-buster
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          go install golang.org/x/lint/golint
          go install honnef.co/go/tools/cmd/staticcheck@2021.1
          go install github.com/ahmetb/govvv@v0.3.0
          make all

      - name: Generate release notes
        run: |
          echo 'RELEASE_NOTES<<EOF' >> $GITHUB_ENV
          make release-notes >> $GITHUB_ENV
          echo >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create prerelease
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Development Build
          prerelease: true
          body: ${{ env.RELEASE_NOTES }}
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add binaries to release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ env.RELEASE_NOTES }}
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Docker build/push
    needs:
      - build
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2       

      - uses: robinraju/release-downloader@v1
        with:
          repository: ${{ github.repository }}
          latest: true
          fileName: gino-keva
          out-file-path: build/
          token: '${{ secrets.GITHUB_TOKEN }}'
      
      - run: chmod +x build/gino-keva
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            philipssoftware/gino-keva
          tags: |
            type=semver,pattern={{version}}

      - name: Login to DockerHub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: philipssoftware/gino-keva
          short-description: ${{ github.event.repository.description }}
