name: Build and Test

# This workflow will run on main branch and on any pull requests targeting main
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  build_linux:
    name: Build - Linux
    runs-on: ubuntu-latest
    container: golang:1.16-buster
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          go get -u golang.org/x/lint/golint
          go install honnef.co/go/tools/cmd/staticcheck@2021.1
          go install github.com/ahmetb/govvv@v0.3.0
          make all

      - name: Generate release notes
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo 'RELEASE_NOTES<<EOF' >> $GITHUB_ENV
          make release-notes >> $GITHUB_ENV
          echo >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Add binaries to release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v0.1.7
        with:
          body: ${{ env.RELEASE_NOTES }}
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_windows:
    name: Build - Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          go get -u golang.org/x/lint/golint
          go install honnef.co/go/tools/cmd/staticcheck@2021.1
          go install github.com/ahmetb/govvv@v0.3.0
          make all
          mv build/gino-keva build/gino-keva.exe

      - name: Add binaries to release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v0.1.7
        with:
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
